version: '3.4'

services:
  samba:
    container_name: samba
    image: dperson/samba:latest
    environment:
      TZ: America/Chicago
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /share:/share:z
    command: '-s "share;/share;yes;no;yes" -p'
