version: "3.7"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/sonarr/config:/config
      - /mnt/truenas/Media/Shows:/tv #optional
      - /opt/docker/volumes/torrent/deluge/downloads:/torrents #optional
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx
