version: "3.7"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    network_mode: service:ts-sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/sonarr/config:/config
      - smb_shows:/media/Shows
      - smb_downloads:/downloads
    restart: unless-stopped

  ts-sonarr:
    image: tailscale/tailscale:latest
    container_name: ts-sonarr
    hostname: ts-sonarr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=sonarr
    volumes:
      - ts-sonarr-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  sonarr-caddy:
    container_name: sonarr-caddy
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:ts-sonarr
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - net_admin
    restart: unless-stopped

volumes:
  ts-sonarr-data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  smb_downloads:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.10.99/Share/Downloads
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,uid=1000
  smb_shows:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.10.99/Media/Shows
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,uid=1000
