services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    network_mode: service:tailscale
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/sonarr/sonarr-config:/config
      - nfs_shows:/media/Shows
      - nfs_downloads:/downloads
    restart: always

  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: sonarr-tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=sonarr
    volumes:
      - /opt/docker/volumes/sonarr/tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  caddy:
    container_name: sonarr-caddy
    build: ../caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:tailscale
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/sonarr/caddy-data:/data
      - /opt/docker/volumes/sonarr/caddy-config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  nfs_downloads:
    driver: local
    driver_opts:
      type: nfs
      device: ":/mnt/Media/Share/Downloads"
      o: "addr=192.168.10.99,nfsvers=4,rw"
  nfs_shows:
    driver: local
    driver_opts:
      type: nfs
      device: ":/mnt/Media/Media/Shows"
      o: "addr=192.168.10.99,nfsvers=4,rw"
