version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:latest
    container_name: hedgedoc_mariadb
    restart: always
    volumes:
      - /opt/docker/volumes/hedgedoc/mariadb:/config
    environment:
      - MYSQL_ROOT_PASSWORD=mariaroot
      - MYSQL_DATABASE=hedgedoc
      - MYSQL_USER=hedgedoc
      - MYSQL_PASSWORD=mariapassword
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
      - CMD_ALLOW_ANONYMOUS=true
  hedgedoc:
    image: ghcr.io/linuxserver/hedgedoc:latest
    container_name: hedgedoc
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /opt/docker/volumes/hedgedoc/config:/config
    environment:
      - DB_HOST=mariadb
      - DB_USER=hedgedoc
      - DB_PASS=mariapassword
      - DB_NAME=hedgedoc
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - "127.0.0.1:3000:3000"
networks:
  default:
    external:
      name: nginx
