version: '3.5'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      TYPE: "PAPER"
      VERSION: "1.19"
    volumes:
      - /opt/docker/volumes/papermc:/data
    ports:
      - "25565:25565"