version: '3.5'

services:
  vanilla:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.19"
      OPS: "lettucebowler"
      WHITELIST: "lettucebowler"
      ENFORCE_WHITELIST: "TRUE"
      DIFFICULTY: "normal"
      ALLOW_NETHER: "TRUE"
      SERVER_NAME: "LettuceCraft"
      MOTD: "Lettuce and friends"
      MEMORY: "2G"
      ONLINE_MODE: "true"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      AUTOPAUSE_TIMEOUT_EST: "1200"
      USE_AIKAR_FLAGS: "TRUE"
      TZ: "America/Chicago"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "4G"
      JVM_DD_OPTS: "disable.watchdog:true"
      VANILLATWEAKS_SHARECODE: "vr27ux,ZNZh6w"
    volumes:
      - /opt/docker/volumes/minecraft/papermc:/data

  router:
    image: itzg/mc-router
    ports:
    - 25565:25565
    command: --mapping=mc.lettucebowler.net=vanilla:25565,vanilla.mc.lettucebowler.net=vanilla:25565

networks:
  default:
    external:
      name: nginx
