version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=lettucebowler.net
      - SUBDOMAINS=deluge, mc, home, plex
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
    volumes:
      - /opt/docker/volumes/gengar-swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    
networks:
  default:
    external:
      name: nginx
