services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: service:tailscale
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/prowlarr/prowlarr-config:/config
    restart: always

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: prowlarr-flaresolverr
    network_mode: service:tailscale
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    restart: always

  tailscale:
    image: tailscale/tailscale:latest
    container_name: prowlarr-tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=prowlarr
    volumes:
      - /opt/docker/volumes/prowlarr/tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  caddy:
    container_name: prowlarr-caddy
    build: ../caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:tailscale
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/prowlarr/caddy-data:/data
      - /opt/docker/volumes/prowlarr/caddy-config:/config
    cap_add:
      - net_admin
    restart: always
