version: "2.1"
services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ORIGIN_URL=${ORIGIN_URL}
      - ORIGIN_USERNAME=${ORIGIN_USERNAME}
      - ORIGIN_PASSWORD=${ORIGIN_PASSWORD}
      - REPLICA_URL=${REPLICA_URL}
      - REPLICA_USERNAME=${REPLICA_USERNAME}
      - REPLICA_PASSWORD=${REPLICA_PASSWORD}
    volumes:
      - /opt/docker/volumes/adguard-sync/config:/config
    ports:
      - 8080:8080
    restart: unless-stopped
