services:
  adguardhome-sync:
    image: ghcr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/volumes/adguard-sync/config:/config
    ports:
      - 8080:8080
    restart: always
