version: "2.1"
    services:
      heimdall:
        image: ghcr.io/linuxserver/heimdall
        container_name: heimdall
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
        volumes:
          - /opt/docker/volumes/heimdall/config:/config
        ports:
          - 81:80
          - 444:443
        restart: unless-stopped