services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - ADVERTISE_IP='https://192.168.10.133,https://plex.lettucebowler.net'
    volumes:
      - /opt/docker/volumes/plex/plex-config:/config
      - nfs_media:/media
      - /tmp:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: always
    network_mode: host

  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: plex-tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=plex
    volumes:
      - /opt/docker/volumes/plex/tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  caddy:
    container_name: plex-caddy
    build: ../caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:tailscale
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/plex/caddy-data:/data
      - /opt/docker/volumes/plex/caddy-config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  nfs_media:
    driver: local
    driver_opts:
      type: nfs
      device: ":/mnt/Media/Media"
      o: "addr=192.168.10.99,nfsvers=4,rw"
