version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /opt/docker/volumes/plex/config:/config
      - /share/Media:/media
      - /tmp:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  plex-proxy:
    image: erisamoe/cloudflared
    container_name: plex-proxy
    volumes:
      - /opt/docker/volumes/cloudflared:/etc/cloudflared
    command: --hostname plex.lettucebowler.net --url http://gengar.local:32400
    depends_on:
      - plex
