services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - ADVERTISE_IP='https://192.168.10.133,https://plex.lettucebowler.net'
    volumes:
      - /opt/docker/volumes/plex/plex-config:/config
      - smb_media:/media
      - /tmp:/transcode
    devices:
      - /dev/dri:/dev/dri
    restart: always
    network_mode: host

  ts-plex:
    image: tailscale/tailscale:latest
    container_name: ts-plex
    hostname: ts-plex
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=plex
    volumes:
      - /opt/docker/volumes/plex/ts-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  caddy-plex:
    container_name: caddy-plex
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:ts-plex
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/plex/caddy-data:/data
      - /opt/docker/volumes/plex/caddy-config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  smb_media:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.10.99/Media
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,uid=1000
