version: '3'
services:
  nginx-proxy-manager:
    container_name: 'nginx-proxy-manager'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /opt/docker/volumes/gengar-proxy/data:/data
      - /opt/docker/volumes/gengar-proxy/letsencrypt:/etc/letsencrypt
  npm-db:
    container_name: 'npm-db'
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - /opt/docker/volumes/gengar-proxy/data/mysql:/var/lib/mysql
networks:
  default:
    external:
      name: nginx