version: "3"
services:
  gitea:
    image: gitea/gitea:1.15
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /opt/docker/volumes/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:3333:3333"
      - "222:22"
    
networks:
  default:
    external:
      name: nginx
