version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'America/Chicago'
    volumes:
      - '/opt/docker/volumes/pihole/etc-pihole:/etc/pihole'
      - '/opt/docker/volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'    
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx
