version: "3"
services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:1.19
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - /opt/docker/volumes/forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2022:22"

networks:
  default:
    external:
      name: nginx
