version: "3.7"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/radarr/config:/config
      - /mnt/truenas/Media/Movies:/movies #optional
      - /opt/docker/volumes/torrent/deluge/downloads:/torrents #optional
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx
