version: "3.7"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/radarr/config:/config
      - /mnt/truenas/Media/Movies:/movies
      - /home/lettucebowler/downloads:/torrents
      - /home/lettucebowler/downloads:/downloads
    restart: unless-stopped

  ts-radarr:
    image: tailscale/tailscale:latest
    container_name: ts-radarr
    hostname: ts-radarr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=radarr
    volumes:
      - ts-radarr-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  radarr-caddy:
    container_name: radarr-caddy
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:ts-radarr
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - net_admin
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx

volumes:
  ts-radarr-data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
