services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    network_mode: service:tailscale
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/radarr/radarr-config:/config
      - smb_movies:/media/Movies
      - smb_downloads:/downloads
    restart: always

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=radarr
    volumes:
      - /opt/docker/volumes/radarr/tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  caddy:
    container_name: radarr-caddy
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:radarr-tailscale
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/radarr/caddy-data:/data
      - /opt/docker/volumes/radarr/caddy-config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  smb_downloads:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.10.99/Share/Downloads
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,uid=1000
  smb_movies:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.10.99/Media/Movies
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,uid=1000
