version: "3.7"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/radarr/config:/config
      - /mnt/truenas/Media/Movies:/movies #optional
      - /opt/docker/volumes/torrent/downloads:/downloads #optional
    restart: unless-stopped

  radarr-proxy:
    image: erisamoe/cloudflared
    container_name: radarr-proxy
    volumes:
      - /opt/docker/volumes/cloudflared:/etc/cloudflared
    command: --hostname radarr.lettucebowler.net --url http://radarr:7878
    depends_on:
      - radarr

networks:
  default:
    external:
      name: nginx
