version: "3.7"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    network_mode: service:ts-radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /opt/docker/volumes/radarr/config:/config
      - smb_movies:/media/Movies
      - smb_downloads:/downloads
    restart: unless-stopped

  ts-radarr:
    image: tailscale/tailscale:latest
    container_name: ts-radarr
    hostname: ts-radarr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=radarr
    volumes:
      - ts-radarr-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  caddy-radarr:
    container_name: caddy-radarr
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:ts-radarr
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - net_admin
    restart: unless-stopped

volumes:
  ts-radarr-data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  smb_downloads:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.10.99/Share/Downloads
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,uid=1000
  smb_movies:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.10.99/Media/Movies
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,uid=1000
