version: "2.1"
services:
  components:
    image: ghcr.io/linuxserver/nginx
    container_name: components
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ../../volumes/components/config:/config
    ports:
      - 127.0.0.1:8085:8085
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx
