version: "3"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
      - target: 3000
        published: 3000
        protocol: tcp
        mode: container
    volumes:
      - /opt/docker/volumes/adguardhome/work:/opt/adguardhome/work
      - /opt/docker/volumes/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx
