version: "3.9"
services:
  lettuce-tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TOKEN}

networks:
  default:
    external:
      name: nginx
