services:
  caddy:
    container_name: gitea-caddy
    build: ../caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:tailscale
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/proxy/caddy-data:/data
      - /opt/docker/volumes/proxy/caddy-config:/config
    cap_add:
      - net_admin
    restart: always
      
  tailscale:
    image: tailscale/tailscale:latest
    container_name: proxy-tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=${TS_HOSTNAME}
    volumes:
      - /opt/docker/volumes/nginx-proxy-manager/tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
