services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
      - /opt/docker/volumes/adguardhome/adguardhome-work:/opt/adguardhome/work
      - /opt/docker/volumes/adguardhome/adguardhome-conf:/opt/adguardhome/conf
    restart: always
    network_mode: host

  tailscale:
    image: tailscale/tailscale:latest
    container_name: adguardhome-tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=${HOSTNAME}
    volumes:
      - /opt/docker/volumes/adguardhome/ts-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  caddy:
    container_name: adguardhome-caddy
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - HOSTNAME=${HOSTNAME}
      - IP_ADDRESS=${IP_ADDRESS}
    network_mode: service:tailscale
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/adguardhome/caddy-data:/data
      - /opt/docker/volumes/adguardhome/caddy-data:/config
    cap_add:
      - net_admin
    restart: always
