services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
      - /opt/docker/volumes/adguardhome/work:/opt/adguardhome/work
      - /opt/docker/volumes/adguardhome/conf:/opt/adguardhome/conf
    restart: always
    network_mode: host

  ts-adguard:
      image: tailscale/tailscale:latest
      container_name: ts-adguard
      environment:
        - TS_AUTHKEY=${TS_AUTHKEY}
        - TS_STATE_DIR=/var/lib/tailscale
        - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
        - TS_HOSTNAME=${HOSTNAME}
      volumes:
        - /opt/docker/volumes/adguard/ts-data:/var/lib/tailscale
        - /dev/net/tun:/dev/net/tun
      cap_add:
        - net_admin
      restart: always

  caddy-adguard:
    container_name: caddy-adguard
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - HOSTNAME=${HOSTNAME}
      - IP_ADDRESS=${IP_ADDRESS}
    network_mode: service:ts-adguard
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/adguardhome/caddy-data:/data
      - /opt/docker/volumes/adguardhome/caddy-data:/config
    cap_add:
      - net_admin
    restart: always