version: "2.1"
services:
  sudoku:
    image: ghcr.io/linuxserver/nginx
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/docker/volumes/deluge:/config
    ports:
      - 8112:8112
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx