services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    user: 1000:1000
    volumes:
      - /opt/docker/volumes/jellyfin/jellyfin-config:/config
      - nfs_media:/media
    devices:
      - /dev/dri:/dev/dri
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - GUID=1000
      - JELLYFIN_PublishedServerUrl=http://jelly.lettucebowler.net
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: jellyfin-tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=jellyfin
    volumes:
      - /opt/docker/volumes/jellyfin/tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  caddy:
    container_name: jellyfin-caddy
    build: ../caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:tailscale
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/jellyfin/caddy-data:/data
      - /opt/docker/volumes/jellyfin/caddy-config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  nfs_media:
    driver: local
    driver_opts:
      type: nfs
      device: ":/mnt/Media/Media"
      o: "addr=192.168.10.99,nfsvers=4,rw"