services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /opt/docker/volumes/jellyfin/config:/config
      - /mnt/truenas/Media/Shows/:/data/tvshows
      - /mnt/truenas/Media/Movies:/data/movies
    ports:
      - 8096:8096
    restart: always
    devices:
      - /dev/dri:/dev/dri
  ts-jellyfin:
    image: tailscale/tailscale:latest
    container_name: ts-jellyfin
    hostname: ts-jellyfin
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=jellyfin
    volumes:
      - ts-jellyfin-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  jellyfin-caddy:
    container_name: jellyfin-caddy
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:ts-jellyfin
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  ts-jellyfin-data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
