services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /opt/docker/volumes/jellyfin/config:/config
      - /mnt/truenas/Media/Shows/:/data/tvshows
      - /mnt/truenas/Media/Movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped