version: '3.8'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee
    restart: always
    depends_on:
      - ts-portainer
    network_mode: service:ts-portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  ts-portainer:
    image: tailscale/tailscale:latest
    container_name: ts-portainer
    hostname: ts-portainer
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=portainer
    volumes:
      - ts-portainer-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  portainer-caddy:
    container_name: portainer-caddy
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:ts-portainer
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  portainer_data:
    external: true
  ts-portainer-data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
