version: "3.7"
services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    network_mode: service:ts-lidarr
    depends_on:
      - ts-lidarr
    volumes:
      - /opt/docker/volumes/lidarr/config:/config
      - smb_music:/music
      - smb_downloads:/downloads
    restart: always

  ts-lidarr:
    image: tailscale/tailscale:latest
    container_name: ts-lidarr
    hostname: ts-lidarr
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=lidarr
    volumes:
      - ts-lidarr-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  lidarr-caddy:
    container_name: lidarr-caddy
    image: iarekylew00t/caddy-cloudflare
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:ts-lidarr
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  ts-lidarr-data:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  smb_downloads:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.10.99/Share/Downloads
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,uid=1000
  smb_music:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.10.99/Media/Movies
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},vers=3.0,uid=1000
