services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    network_mode: service:tailscale
    volumes:
      - /opt/docker/volumes/lidarr/lidarr-config:/config
      - nfs_music:/media/music
      - nfs_downloads:/downloads
    restart: always

  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: lidarr-tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=lidarr
    volumes:
      - /opt/docker/volumes/lidarr/tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  caddy:
    container_name: lidarr-caddy
    build: ../caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:tailscale
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/lidarr/caddy-data:/data
      - /opt/docker/volumes/lidarr/caddy-config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  nfs_downloads:
    driver: local
    driver_opts:
      type: nfs
      device: ":/mnt/Media/Share/Downloads"
      o: "addr=192.168.10.99,nfsvers=4,rw"
  nfs_music:
    driver: local
    driver_opts:
      type: nfs
      device: ":/mnt/Media/Media/Music"
      o: "addr=192.168.10.99,nfsvers=4,rw"
