services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    network_mode: service:tailscale
    volumes:
      - nfs_downloads:/downloads

  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: metube-tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--reset --advertise-tags=tag:container
      - TS_HOSTNAME=metube
    volumes:
      - /opt/docker/volumes/metube/tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  caddy:
    container_name: metube-caddy
    build: ../caddy
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    network_mode: service:tailscale
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /opt/docker/volumes/metube/caddy-data:/data
      - /opt/docker/volumes/metube/caddy-config:/config
    cap_add:
      - net_admin
    restart: always

volumes:
  nfs_downloads:
    driver: local
    driver_opts:
      type: nfs
      device: ":/mnt/Media/Share/Downloads"
      o: "addr=192.168.10.99,nfsvers=4,rw"