services:
  tsdproxy:
    image: ghcr.io/almeidapaulopt/tsdproxy:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/volumes/tsdproxy/tsdproxy-data:/data
      - /opt/docker/volumes/tsdproxy/tsdproxy-config:/config
    restart: unless-stopped
    ports:
      - "8080:8080"